ALTER TABLE _Account	ADD CONSTRAINT Account_PK	PRIMARY KEY NONCLUSTERED (AID)
ALTER TABLE _Character	ADD CONSTRAINT Character_PK PRIMARY KEY NONCLUSTERED (CID)
ALTER TABLE _Clan		ADD CONSTRAINT Clan_PK		PRIMARY KEY NONCLUSTERED (CLID)
ALTER TABLE _ClanMember	ADD CONSTRAINT ClanMember_PK PRIMARY KEY NONCLUSTERED (CMID)
ALTER TABLE _Login		ADD CONSTRAINT Login_PK		PRIMARY KEY NONCLUSTERED (UserID)

CREATE UNIQUE NONCLUSTERED INDEX UIX_Account_UserID	ON _Account(UserID)

CREATE NONCLUSTERED INDEX IX_Account_DeleteFlag		ON _Account(DeleteFlag)
CREATE NONCLUSTERED INDEX IX_Account_LastLogoutTime ON _Account(LastLogoutTime)

CREATE NONCLUSTERED INDEX IX_Character_AID				ON _Character(AID)
CREATE NONCLUSTERED INDEX IX_Character_AID_DeleteFlag	ON _Character(AID, DeleteFlag)
CREATE NONCLUSTERED INDEX IX_Character_AID_CharNum		ON _Character(AID, CharNum)
CREATE NONCLUSTERED INDEX IX_Character_DeleteFlag		ON _Character(DeleteFlag)
CREATE NONCLUSTERED INDEX IX_Character_Name				ON _Character(Name)

CREATE NONCLUSTERED INDEX IX_Clan_MasterCID		ON _Clan(MasterCID)
CREATE NONCLUSTERED INDEX IX_Clan_DeleteFlag	ON _Clan(DeleteFlag)
CREATE NONCLUSTERED INDEX IX_Clan_Name			ON _Clan(Name)

CREATE NONCLUSTERED INDEX IX_ClanMember_CLID_CID ON _ClanMember(CID, CLID)
CREATE NONCLUSTERED INDEX IX_ClanMember_CID_CLID ON _ClanMember(CLID, CID)

CREATE NONCLUSTERED INDEX IX_Friend_CID			ON _Friend(CID)
CREATE NONCLUSTERED INDEX IX_Friend_FriendCID	ON _Friend(FriendCID)


